apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar-ms
  labels:
    microservice: bar-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: bar-ms
  template:
    metadata:
      labels:
        microservice: bar-ms
    spec:
      containers:
        - name: bar-ms
          image: bar:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.1"
              memory: "128Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"
